CREATE TABLE Quiz (
    ID INT PRIMARY KEY IDENTITY(1,1), 
    Title VARCHAR(255) NOT NULL, 
    Artist VARCHAR(255) NOT NULL, 
    Lyrics TEXT NOT NULL, 
    Answer VARCHAR(255) NOT NULL
);

CREATE TABLE Person (
    ID INT PRIMARY KEY IDENTITY(1,1),
    Username VARCHAR(255) NOT NULL,
    Password VARCHAR(255) NOT NULL, 
    Score INT
);